version: '3'
services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: beelineDB

  profileservice:
    image: scoobymax/profileservice:1.0-SNAPSHOT
    hostname: profileservice
    container_name: profileservice
    expose:
      - "8080"
    ports:
      - "8081:8080"

  detailservice:
    image: scoobymax/detailservice:1.0-SNAPSHOT
    hostname: detailservice
    container_name: detailservice
    links:
      - postgres
    expose:
      - "8080"
    ports:
      - "80:8080"
    depends_on:
      - postgres
      - profileservice

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080