version: '3'
services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: beelineDB

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  beeline:
    image: scoobymax/beeline
    hostname: beeline
    container_name: beeline
    links:
      - postgres
    expose:
      - "8080"
    ports:
      - "80:8080"
    depends_on:
      - postgres