# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
#    - name: Sonar verify
#      run: mvn -B clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar
    - name: Analyze with SonarCloud
      run: ./mvnw -B clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -Dsonar.projectKey=ScoobyMax_Beeline -Dsonar.organization=scoobymax -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
      env:
       GITHUB_TOKEN: ${{ secrets.TEMP_TOKEN }}
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: CodeCov
      run: bash <(curl -s https://codecov.io/bash)
    - name: Build with Maven
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: mvn -B install -s ./settings.xml
